name: Build and Upload Artifacts on Release

on:
  release:
    types: [published] # 只在正式发布时触发，如果需要草稿或预发布可添加: created, prereleased

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # 根据你的项目类型选择合适的构建工具，比如 Maven/Gradle/npm
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.9'
      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.ECLIPSE_GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import --yes --quiet --no-tty
          gpg --list-keys

      - name: Build with Maven (PGP signing)
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.ECLIPSE_GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ secrets.ECLIPSE_GPG_KEY_ID }}
        run: |
          mvn -B clean verify -ntp -DskipTests -Psign \
            -Dgpg.keyname="${GPG_KEY_ID}"

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: sites/com.tlcsdm.eclipse.openexplorer.site/target/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
